spring.application.name=firstproject
server.servlet.encoding.force=true
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

# JPA 로깅 설정
# 디버그 레벨 설정
# SQL 쿼리 로그 출력
logging.level.org.hibernate.SQL=DEBUG

# SQL 보기 좋게 줄바꿈 정렬
spring.jpa.properties.hibernate.format_sql=true

# SQL 매개변수 값 출력
logging.level.org.hibernate.descriptor.sql.BasicBinder=TRACE

# DB URL 설정
# 고유한 URL을 생성하지 않음
spring.datasource.generate-unique-name=false

# JDBC 데이터베이스 URL 설정
# spring.datasource.url=jdbc:h2:mem:testdb

# PostgreSQL 연동
spring.datasource.url=jdbc:postgresql://localhost:5432/firstproject_db
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.datasource.data=classpath:/data.sql
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update


